### ISSUE TITLE
Deprecation Notification

### ISSUE THREAD

**Issue by Jahhein** [uonick/dimmed-dark-ocean-syntax#1]
Getting a deprecation error with this theme.

> Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated > within a shadow DOM boundary. 
> This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your
> syntax selectors with syntax--. 
> To prevent breakage with existing style sheets, Atom will  automatically upgrade the following selectors:

**Comment by uonick** [comment]
Hi, @Jahhein ! 
Thank you for reporting this. This theme is deprecated and is no longer supported and replaced by https://github.com/uonick/dimmed-one-dark-syntax (base16 palette too)

If you want to fix a bug:
* PR requests are welcome
* wait for my free time

**Comment by Jahhein** [comment]
Oops, I didn't realize it was no longer updated. I didn't see that anywhere. Glad to know there is an alternative! Thank you.

**Comment by uonick** [comment]
I pushed new version just now 🎉 
if you have any questions, please contact with new issue

**Comment by Jahhein** [comment]
@uonick you're awesome! Thank you!
